/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PrivatlivspolitikRouteImport } from './routes/privatlivspolitik'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServiceEssentialRouteImport } from './routes/service.essential'
import { Route as ServiceHousekeepingRouteImport } from './routes/service.housekeeping'
import { Route as ServiceSignatureRouteImport } from './routes/service.signature'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivatlivspolitikRoute = PrivatlivspolitikRouteImport.update({
  id: '/privatlivspolitik',
  path: '/privatlivspolitik',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceEssentialRoute = ServiceEssentialRouteImport.update({
  id: '/service/essential',
  path: '/service/essential',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceHousekeepingRoute = ServiceHousekeepingRouteImport.update({
  id: '/service/housekeeping',
  path: '/service/housekeeping',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceSignatureRoute = ServiceSignatureRouteImport.update({
  id: '/service/signature',
  path: '/service/signature',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/privatlivspolitik': typeof PrivatlivspolitikRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/service/essential': typeof ServiceEssentialRoute
  '/service/housekeeping': typeof ServiceHousekeepingRoute
  '/service/signature': typeof ServiceSignatureRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/privatlivspolitik': typeof PrivatlivspolitikRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/service/essential': typeof ServiceEssentialRoute
  '/service/housekeeping': typeof ServiceHousekeepingRoute
  '/service/signature': typeof ServiceSignatureRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/privatlivspolitik': typeof PrivatlivspolitikRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/service/essential': typeof ServiceEssentialRoute
  '/service/housekeeping': typeof ServiceHousekeepingRoute
  '/service/signature': typeof ServiceSignatureRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/privatlivspolitik'
    | '/sitemap.xml'
    | '/service/essential'
    | '/service/housekeeping'
    | '/service/signature'
    | '/lovable/email/transactional/preview'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/privatlivspolitik'
    | '/sitemap.xml'
    | '/service/essential'
    | '/service/housekeeping'
    | '/service/signature'
    | '/lovable/email/transactional/preview'
  id:
    | '__root__'
    | '/'
    | '/privatlivspolitik'
    | '/sitemap.xml'
    | '/service/essential'
    | '/service/housekeeping'
    | '/service/signature'
    | '/lovable/email/transactional/preview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PrivatlivspolitikRoute: typeof PrivatlivspolitikRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ServiceEssentialRoute: typeof ServiceEssentialRoute
  ServiceHousekeepingRoute: typeof ServiceHousekeepingRoute
  ServiceSignatureRoute: typeof ServiceSignatureRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privatlivspolitik': {
      id: '/privatlivspolitik'
      path: '/privatlivspolitik'
      fullPath: '/privatlivspolitik'
      preLoaderRoute: typeof PrivatlivspolitikRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service/essential': {
      id: '/service/essential'
      path: '/service/essential'
      fullPath: '/service/essential'
      preLoaderRoute: typeof ServiceEssentialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service/housekeeping': {
      id: '/service/housekeeping'
      path: '/service/housekeeping'
      fullPath: '/service/housekeeping'
      preLoaderRoute: typeof ServiceHousekeepingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service/signature': {
      id: '/service/signature'
      path: '/service/signature'
      fullPath: '/service/signature'
      preLoaderRoute: typeof ServiceSignatureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PrivatlivspolitikRoute: PrivatlivspolitikRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ServiceEssentialRoute: ServiceEssentialRoute,
  ServiceHousekeepingRoute: ServiceHousekeepingRoute,
  ServiceSignatureRoute: ServiceSignatureRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
